import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import Message from "../components/Message";
import { db } from "../utils/firebase";

export default function Home() {
  const [posts, setPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="my-8">
        <h2 className="text-xl">See what people are saying:</h2>
        <div>
          {posts.map((post) => (
            <Message key={post.id} post={post}>
              <Link href={{ pathname: `/post/${post.id}`, query: post }}>
                <button className="mt-4 text-cyan-600 text-sm">
                  {post.comments?.length > 0 ? post.comments.length : 0}{" "}
                  comments
                </button>
              </Link>
            </Message>
          ))}
        </div>
      </main>
    </div>
  );
}
